#ifndef WATERLINKED_SONAR_DRIVER_H
#define WATERLINKED_SONAR_DRIVER_H

#include <array>
#include <atomic>
#include <builtin_interfaces/msg/time.hpp>
#include <chrono>
#include <cstdint>
#include <diagnostic_updater/diagnostic_updater.hpp>
#include <memory>
#include <rclcpp_lifecycle/lifecycle_node.hpp>
#include <rclcpp_lifecycle/lifecycle_publisher.hpp>
#include <sensor_msgs/msg/camera_info.hpp>
#include <sensor_msgs/msg/image.hpp>
#include <sensor_msgs/msg/imu.hpp>
#include <sensor_msgs/msg/point_cloud2.hpp>
#include <std_srvs/srv/set_bool.hpp>
#include <string>
#include <utility>
#include <vector>
#include <waterlinked_sonar_driver/srv/set_range.hpp>
#include <waterlinkedsonar/client.hpp>
#include <waterlinkedsonar/conversions.hpp>
#include <waterlinkedsonar/receiver.hpp>
#include <waterlinkedsonar/sntp.hpp>

// auto-generated by generate_parameter_library
#include <waterlinked_sonar_driver/waterlinked_sonar_driver_parameters.hpp>

namespace waterlinked::sonar::ros {

using CallbackReturn =
    rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;

// Threading: the executor thread runs lifecycle transitions and the
// diagnostics timers; the library's receive thread runs the message handlers
// and publishes. Only the publishers (thread-safe) are shared between the two,
// so nothing here needs a lock. Everything else is either executor-only
// (client_, receiver_ pointer, hardware-poll snapshot) or receive-thread-only
// (message buffers, scratch vectors).
class WaterlinkedSonarDriver : public rclcpp_lifecycle::LifecycleNode {
 public:
  explicit WaterlinkedSonarDriver(
      const rclcpp::NodeOptions& options = rclcpp::NodeOptions());

  CallbackReturn on_configure(
      const rclcpp_lifecycle::State& previous_state) override;
  CallbackReturn on_activate(
      const rclcpp_lifecycle::State& previous_state) override;
  CallbackReturn on_deactivate(
      const rclcpp_lifecycle::State& previous_state) override;
  CallbackReturn on_cleanup(
      const rclcpp_lifecycle::State& previous_state) override;
  CallbackReturn on_shutdown(
      const rclcpp_lifecycle::State& previous_state) override;

 private:
  bool apply_sonar_configuration();
  bool configure_ntp();

  // Receive-thread handlers.
  void handle_range_image(const RangeImageView& img);
  void handle_bitmap_image(const BitmapImageView& img);
  void handle_imu_batch(const ImuBatchView& batch);
  void publish_camera_info(const builtin_interfaces::msg::Time& stamp,
                           std::uint32_t width, std::uint32_t height,
                           float fov_horizontal_deg, float fov_vertical_deg);
  builtin_interfaces::msg::Time stamp_for(std::int64_t timestamp_ns);

  // Executor-thread diagnostics.
  void poll_hardware();
  void receiver_diagnostics(diagnostic_updater::DiagnosticStatusWrapper& stat);
  void hardware_diagnostics(diagnostic_updater::DiagnosticStatusWrapper& stat);

  std::shared_ptr<waterlinked_sonar_driver::ParamListener> param_listener_;
  waterlinked_sonar_driver::Params params_;

  std::unique_ptr<SonarClient> client_;
  std::unique_ptr<Receiver> receiver_;

  rclcpp_lifecycle::LifecyclePublisher<sensor_msgs::msg::PointCloud2>::SharedPtr
      point_cloud_pub_;
  rclcpp_lifecycle::LifecyclePublisher<sensor_msgs::msg::Image>::SharedPtr
      range_image_pub_;
  rclcpp_lifecycle::LifecyclePublisher<sensor_msgs::msg::Image>::SharedPtr
      intensity_image_pub_;
  rclcpp_lifecycle::LifecyclePublisher<sensor_msgs::msg::CameraInfo>::SharedPtr
      camera_info_pub_;
  rclcpp_lifecycle::LifecyclePublisher<sensor_msgs::msg::Imu>::SharedPtr
      imu_pub_;

  rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr enable_acoustics_srv_;
  rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr enable_high_frequency_srv_;
  rclcpp::Service<waterlinked_sonar_driver::srv::SetRange>::SharedPtr
      set_range_srv_;

  std::unique_ptr<diagnostic_updater::Updater> diagnostics_;
  rclcpp::TimerBase::SharedPtr hardware_poll_timer_;

  // Snapshot from the last HTTP poll, read back by hardware_diagnostics().
  unsigned char hardware_level_{0};
  std::string hardware_message_;
  std::vector<std::pair<std::string, std::string>> hardware_values_;

  std::chrono::steady_clock::time_point activated_at_;

  // Receive-thread state.
  std::array<float, 4> last_geometry_{};  // width, height, fov_h, fov_v
  std::vector<float> points_scratch_;
  std::vector<float> distances_scratch_;
  sensor_msgs::msg::PointCloud2 cloud_msg_;
  sensor_msgs::msg::Image range_msg_;
  sensor_msgs::msg::Image intensity_msg_;
  sensor_msgs::msg::CameraInfo camera_info_msg_;
  sensor_msgs::msg::Imu imu_msg_;
  std::atomic<std::uint64_t> shaded_images_dropped_{0};
  std::atomic<std::uint64_t> invalid_geometry_{0};
};

}  // namespace waterlinked::sonar::ros

#endif  // WATERLINKED_SONAR_DRIVER_H
